// Mocks generated by Mockito 5.0.8 from annotations
// in handcash_connect_sdk/test/src/link/link_handler_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:handcash_connect_sdk/src/link/link_listener.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [LinkListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkListener extends _i1.Mock implements _i2.LinkListener {
  MockLinkListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Uri?> getUriLinksStream() =>
      (super.noSuchMethod(Invocation.method(#getUriLinksStream, []),
          returnValue: Stream<Uri?>.empty()) as _i3.Stream<Uri?>);
  @override
  _i3.Future<Uri?> getInitialUri() =>
      (super.noSuchMethod(Invocation.method(#getInitialUri, []),
          returnValue: Future<Uri?>.value()) as _i3.Future<Uri?>);
}
