name: Publish package on Pub.dev

on: 
  push:
    branches:
       - "master"

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Upload package'
        id: 'upload'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          format: true
          skipTests: true
        
      - run: echo "Package is published ${{ steps.upload.outputs.success }}"
      - run: echo "Package local version is ${{ steps.upload.outputs.localVersion }}"
      - run: echo "Package published version is ${{ steps.upload.outputs.remoteVersion }}"
      - run: echo "Dart version used ${{ steps.upload.outputs.dartVersion }}"
      - run: echo "Flutter version used ${{ steps.upload.outputs.flutterVersion }}"
