name: Package tests CI

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run test
        run: flutter test
        env:
          test_authToken: ${{ secrets.TEST_AUTH_TOKEN }}
